export const themes = [
  {
    title: "Ching (Yijing) Theme",
    path: "/ching-theme",
    img: "/src/assets/images/theme1.jpeg",
    imgAltText: "Ching-theme-image",
  },
  {
    title: "Shinto Omikuji Theme",
    path: "/shinto-theme",
    img: "/src/assets/images/theme2.jpeg",
    imgAltText: "Shinto-theme-image",
  },
  {
    title: "Vedic Theme",
    path: "/vedic-theme",
    img: "/src/assets/images/theme3.jpeg",
    imgAltText: "Vedic-theme-image",
  },
  {
    title: "Celtic Rune Theme",
    path: "/celtic-theme",
    img: "/src/assets/images/theme4.webp",
    imgAltText: "Celtic-theme-image",
  },
  {
    title: "Egyptian Ma'at Theme",
    path: "/egypt-theme",
    img: "/src/assets/images/theme5.webp",
    imgAltText: "Egypt-theme-image",
  },
  {
    title: "African Divination Theme",
    path: "/african-theme",
    img: "/src/assets/images/theme6.webp",
    imgAltText: "African-theme-image",
  },
  {
    title: "Roman Fortuna Theme",
    path: "/roman-theme",
    img: "/src/assets/images/theme7.webp",
    imgAltText: "Roman-theme-image",
  },
  {
    title: "Native American Spirit Theme",
    path: "/native-theme",
    img: "/src/assets/images/theme8.webp",
    imgAltText: "Native-american-theme-image",
  },
  {
    title: "Mayan Sun Calendar Theme",
    path: "/",
    img: "/src/assets/images/theme9.webp",
    imgAltText: "Calender-theme-image",
  },
  {
    title: "Greek Oracle of Delphi Theme",
    path: "/",
    img: "/src/assets/images/theme10.webp",
    imgAltText: "Greek-theme-image",
  },
  {
    title: "Zoroastrian Good vs Evil Theme",
    path: "/",
    img: "/src/assets/images/theme11.webp",
    imgAltText: "Zoroastrian-theme-image",
  },
  {
    title: "Christian Cross or Crown Theme",
    path: "/",
    img: "/src/assets/images/theme12.webp",
    imgAltText: "Christian-theme-image",
  },
  {
    title: "Islamic Taqdir (Destiny) Theme",
    path: "/",
    img: "/src/assets/images/theme13.webp",
    imgAltText: "Islamic-theme-image",
  },
  {
    title: "Judaism Mazel Theme",
    path: "/",
    img: "/src/assets/images/theme14.webp",
    imgAltText: "Judaism-theme-image",
  },
];
