export const hexagrams = [
  {
    number: 1,
    name: "乾",
    pinyin: "Qián",
    meaning: "The Creative",
    interpretations: [
      "Symbolizes pure creative energy and innovative force.",
      "Encourages leadership and bold initiatives.",
      "Represents a time for dynamic activity and exertion of influence.",
    ],
  },
  {
    number: 2,
    name: "坤",
    pinyin: "Kūn",
    meaning: "The Receptive",
    interpretations: [
      "Signifies receptivity, patience, and nurturing support.",
      "Emphasizes the importance of yielding and adaptability.",
      "Promotes the power of receptiveness and collaboration.",
    ],
  },
  {
    number: 3,
    name: "屯",
    pinyin: "Zhūn",
    meaning: "Difficulty at the Beginning",
    interpretations: [
      "Represents initial challenges and obstacles at the start.",
      "Advises perseverance and resilience through difficult times.",
      "Encourages overcoming obstacles with patience and determination.",
    ],
  },
  {
    number: 4,
    name: "蒙",
    pinyin: "Méng",
    meaning: "Youthful Folly",
    interpretations: [
      "Highlights immaturity and the need for guidance.",
      "Suggests openness to learning and acquiring wisdom.",
      "Warns against rash actions and encourages seeking knowledge.",
    ],
  },
  {
    number: 5,
    name: "需",
    pinyin: "Xū",
    meaning: "Waiting (Nourishment)",
    interpretations: [
      "Suggests waiting for the right time to act.",
      "Emphasizes patience and preparation.",
      "Advises gathering strength and resources before proceeding.",
    ],
  },
  {
    number: 6,
    name: "讼",
    pinyin: "Sòng",
    meaning: "Conflict",
    interpretations: [
      "Represents conflicts and disputes that need resolution.",
      "Advises seeking mediation and finding equitable solutions.",
      "Warns of potential legal or interpersonal conflicts.",
    ],
  },
  {
    number: 7,
    name: "师",
    pinyin: "Shī",
    meaning: "The Army",
    interpretations: [
      "Symbolizes organized effort and discipline.",
      "Encourages strategic planning and strong leadership.",
      "Represents a time for collective effort and unity.",
    ],
  },
  {
    number: 8,
    name: "比",
    pinyin: "Bǐ",
    meaning: "Holding Together",
    interpretations: [
      "Promotes unity and strength through collaboration.",
      "Advises building strong networks and alliances.",
      "Emphasizes the importance of community and mutual support.",
    ],
  },
  {
    number: 9,
    name: "小畜",
    pinyin: "Xiǎo Chù",
    meaning: "The Taming Power of the Small",
    interpretations: [
      "Encourages subtlety and gradual progress.",
      "Advocates for the power of gentle persuasion and influence.",
      "Suggests restraint and attention to small details.",
    ],
  },
  {
    number: 10,
    name: "履",
    pinyin: "Lǚ",
    meaning: "Treading (Conduct)",
    interpretations: [
      "Warns to proceed with caution and be mindful of conduct.",
      "Highlights the importance of careful and respectful behavior.",
      "Encourages maintaining integrity and awareness of surroundings.",
    ],
  },
  {
    number: 11,
    name: "泰",
    pinyin: "Tài",
    meaning: "Peace",
    interpretations: [
      "Symbolizes harmony and a prosperous period.",
      "Encourages fostering peaceful and fruitful relationships.",
      "Represents balance and success in endeavors.",
    ],
  },
  {
    number: 12,
    name: "否",
    pinyin: "Pǐ",
    meaning: "Standstill (Stagnation)",
    interpretations: [
      "Represents a time of stagnation and obstacles.",
      "Advises patience and maintaining faith during difficulties.",
      "Warns of a potential halt in progress and need for reflection.",
    ],
  },
  {
    number: 13,
    name: "同人",
    pinyin: "Tóng Rén",
    meaning: "Fellowship with Men",
    interpretations: [
      "Highlights the value of community and social connections.",
      "Encourages open and harmonious interactions.",
      "Fosters unity and mutual support among people.",
    ],
  },
  {
    number: 14,
    name: "大有",
    pinyin: "Dà Yǒu",
    meaning: "Possession in Great Measure",
    interpretations: [
      "Symbolizes great abundance and prosperity.",
      "Encourages generosity and wise management of resources.",
      "Represents successful endeavors and wealth accumulation.",
    ],
  },
  {
    number: 15,
    name: "谦",
    pinyin: "Qiān",
    meaning: "Modesty",
    interpretations: [
      "Encourages humility and modesty in success.",
      "Promotes simplicity and avoiding arrogance.",
      "Advises restraint and recognizing the value of humility.",
    ],
  },
  {
    number: 16,
    name: "豫",
    pinyin: "Yù",
    meaning: "Enthusiasm",
    interpretations: [
      "Symbolizes joy and enthusiasm in pursuing goals.",
      "Encourages inspiration and motivation.",
      "Represents a time for positive energy and celebration.",
    ],
  },
  {
    number: 17,
    name: "随",
    pinyin: "Suí",
    meaning: "Following",
    interpretations: [
      "Highlights the importance of adaptability and flexibility.",
      "Encourages support and alignment with others.",
      "Promotes flow and adjustment to changing circumstances.",
    ],
  },
  {
    number: 18,
    name: "蛊",
    pinyin: "Gǔ",
    meaning: "Work on what has been Spoiled (Decay)",
    interpretations: [
      "Represents the need to address decay and neglect.",
      "Encourages restoration and corrective measures.",
      "Advises improvement and renewal of past mistakes.",
    ],
  },
  {
    number: 19,
    name: "临",
    pinyin: "Lín",
    meaning: "Approach",
    interpretations: [
      "Symbolizes progress and approaching success.",
      "Encourages openness and engagement.",
      "Represents a period of growth and positive momentum.",
    ],
  },
  {
    number: 20,
    name: "观",
    pinyin: "Guān",
    meaning: "Contemplation",
    interpretations: [
      "Advises reflection and thoughtful observation.",
      "Encourages gaining insight through contemplation.",
      "Highlights the importance of perspective and understanding.",
    ],
  },
  {
    number: 21,
    name: "噬嗑",
    pinyin: "Shì Kè",
    meaning: "Biting Through",
    interpretations: [
      "Represents confronting and resolving obstacles.",
      "Encourages addressing issues directly.",
      "Promotes justice and decisive action.",
    ],
  },
  {
    number: 22,
    name: "贲",
    pinyin: "Bì",
    meaning: "Grace",
    interpretations: [
      "Symbolizes beauty and elegance in presentation.",
      "Encourages appreciating aesthetics and refinement.",
      "Represents enhancing and embellishing the ordinary.",
    ],
  },
  {
    number: 23,
    name: "剥",
    pinyin: "Bō",
    meaning: "Splitting Apart",
    interpretations: [
      "Represents deterioration and separation.",
      "Advises acknowledging and addressing decline.",
      "Warns against ignoring signs of erosion and needed changes.",
    ],
  },
  {
    number: 24,
    name: "复",
    pinyin: "Fù",
    meaning: "Return",
    interpretations: [
      "Symbolizes return and renewal after adversity.",
      "Encourages cyclical growth and new beginnings.",
      "Represents a fresh start and renewal of energy.",
    ],
  },
  {
    number: 25,
    name: "无妄",
    pinyin: "Wú Wàng",
    meaning: "Innocence (The Unexpected)",
    interpretations: [
      "Emphasizes naturalness and simplicity.",
      "Encourages acting without ulterior motives.",
      "Represents spontaneity and genuine actions.",
    ],
  },
  {
    number: 26,
    name: "大畜",
    pinyin: "Dà Chù",
    meaning: "The Taming Power of the Great",
    interpretations: [
      "Symbolizes the potential that is being restrained.",
      "Encourages strength through self-control and discipline.",
      "Represents latent potential and preparation.",
    ],
  },
  {
    number: 27,
    name: "颐",
    pinyin: "Yí",
    meaning: "Nourishment",
    interpretations: [
      "Encourages nourishing the body, mind, and spirit.",
      "Advises attention to health and well-being.",
      "Represents the importance of nurturing relationships.",
    ],
  },
  {
    number: 28,
    name: "大过",
    pinyin: "Dà Guò",
    meaning: "Preponderance of the Great",
    interpretations: [
      "Represents overwhelming excess and imbalance.",
      "Warns against overextending and taking on too much.",
      "Encourages finding balance and addressing excess.",
    ],
  },
  {
    number: 29,
    name: "坎",
    pinyin: "Kǎn",
    meaning: "The Abysmal (Water)",
    interpretations: [
      "Represents facing danger and uncertainty.",
      "Encourages courage and perseverance in adversity.",
      "Advises caution and adaptability in uncertain situations.",
    ],
  },
  {
    number: 30,
    name: "离",
    pinyin: "Lí",
    meaning: "The Clinging, Fire",
    interpretations: [
      "Symbolizes clarity and awareness.",
      "Encourages insight and enlightenment.",
      "Represents attaching and depending on the right things.",
    ],
  },
  {
    number: 31,
    name: "咸",
    pinyin: "Xián",
    meaning: "Influence (Wooing)",
    interpretations: [
      "Encourages mutual influence and attraction.",
      "Advises responsiveness to emotional connections.",
      "Represents the beginning of affectionate relationships.",
    ],
  },
  {
    number: 32,
    name: "恒",
    pinyin: "Héng",
    meaning: "Duration",
    interpretations: [
      "Symbolizes endurance and stable development.",
      "Encourages consistency and perseverance.",
      "Represents maintaining stability over time.",
    ],
  },
  {
    number: 33,
    name: "遯",
    pinyin: "Dùn",
    meaning: "Retreat",
    interpretations: [
      "Advises retreating to safety and regrouping.",
      "Encourages strategic withdrawal from difficult situations.",
      "Warns against over-exposure and suggests taking a step back.",
    ],
  },
  {
    number: 34,
    name: "大壮",
    pinyin: "Dà Zhuàng",
    meaning: "The Power of the Great",
    interpretations: [
      "Symbolizes great strength and energy.",
      "Encourages confident and decisive actions.",
      "Represents harnessing power effectively and wisely.",
    ],
  },
  {
    number: 35,
    name: "晋",
    pinyin: "Jìn",
    meaning: "Progress",
    interpretations: [
      "Represents progressive movement and growth.",
      "Encourages taking advantage of opportunities.",
      "Signifies a time of advancement and improvement.",
    ],
  },
  {
    number: 36,
    name: "明夷",
    pinyin: "Míng Yí",
    meaning: "Darkening of the Light",
    interpretations: [
      "Represents adversity and temporary setbacks.",
      "Advises caution and protecting oneself from harm.",
      "Symbolizes enduring trials with integrity.",
    ],
  },
  {
    number: 37,
    name: "家人",
    pinyin: "Jiā Rén",
    meaning: "The Family",
    interpretations: [
      "Highlights the importance of family and domestic life.",
      "Encourages creating harmony and order at home.",
      "Represents the roles and responsibilities within a family.",
    ],
  },
  {
    number: 38,
    name: "睽",
    pinyin: "Kuí",
    meaning: "Opposition",
    interpretations: [
      "Represents conflicting interests and opposition.",
      "Encourages understanding and reconciling differences.",
      "Advises seeking common ground and resolution.",
    ],
  },
  {
    number: 39,
    name: "蹇",
    pinyin: "Jiǎn",
    meaning: "Obstruction",
    interpretations: [
      "Symbolizes obstacles and impediments.",
      "Advises seeking help and finding alternative paths.",
      "Encourages persistence and strategic navigation.",
    ],
  },
  {
    number: 40,
    name: "解",
    pinyin: "Xiè",
    meaning: "Deliverance",
    interpretations: [
      "Represents release from tensions and constraints.",
      "Encourages solutions and liberation from problems.",
      "Promotes resolving conflicts and finding peace.",
    ],
  },
  {
    number: 41,
    name: "损",
    pinyin: "Sǔn",
    meaning: "Decrease",
    interpretations: [
      "Symbolizes reduction and sacrifice for a greater goal.",
      "Advises giving up excess and prioritizing what's essential.",
      "Encourages frugality and measured decisions.",
    ],
  },
  {
    number: 42,
    name: "益",
    pinyin: "Yì",
    meaning: "Increase",
    interpretations: [
      "Represents growth and increase of resources.",
      "Encourages generosity and sharing of prosperity.",
      "Signifies a positive period of gain and expansion.",
    ],
  },
  {
    number: 43,
    name: "夬",
    pinyin: "Guài",
    meaning: "Breakthrough",
    interpretations: [
      "Symbolizes a breakthrough and resolution of issues.",
      "Encourages decisive and assertive actions.",
      "Represents bold moves and a call to action.",
    ],
  },
  {
    number: 44,
    name: "姤",
    pinyin: "Gòu",
    meaning: "Coming to Meet",
    interpretations: [
      "Represents an important encounter or influence.",
      "Encourages openness and engagement with new opportunities.",
      "Warns about considering potential consequences of encounters.",
    ],
  },
  {
    number: 45,
    name: "萃",
    pinyin: "Cuì",
    meaning: "Gathering Together",
    interpretations: [
      "Symbolizes gathering and the strength of unity.",
      "Encourages cooperation and community building.",
      "Represents the importance of shared goals and efforts.",
    ],
  },
  {
    number: 46,
    name: "升",
    pinyin: "Shēng",
    meaning: "Pushing Upward",
    interpretations: [
      "Represents progress and upward movement.",
      "Encourages dedication and steady efforts.",
      "Signifies a time for ambition and advancement.",
    ],
  },
  {
    number: 47,
    name: "困",
    pinyin: "Kùn",
    meaning: "Oppression (Exhaustion)",
    interpretations: [
      "Symbolizes oppression and exhaustion.",
      "Advises perseverance through difficult times.",
      "Encourages finding inner strength and resilience.",
    ],
  },
  {
    number: 48,
    name: "井",
    pinyin: "Jǐng",
    meaning: "The Well",
    interpretations: [
      "Represents essential resources and community support.",
      "Encourages replenishing and maintaining vital resources.",
      "Symbolizes nourishment and the source of life.",
    ],
  },
  {
    number: 49,
    name: "革",
    pinyin: "Gé",
    meaning: "Revolution (Molting)",
    interpretations: [
      "Symbolizes transformation and significant change.",
      "Encourages adapting to new circumstances.",
      "Represents the need for revolutionary change and reform.",
    ],
  },
  {
    number: 50,
    name: "鼎",
    pinyin: "Dǐng",
    meaning: "The Cauldron",
    interpretations: [
      "Represents a foundation of nourishment and support.",
      "Encourages the cultivation of core values and virtues.",
      "Symbolizes stability and the inheritances of tradition.",
    ],
  },
  {
    number: 51,
    name: "震",
    pinyin: "Zhèn",
    meaning: "The Arousing (Shock, Thunder)",
    interpretations: [
      "Represents awakening and sudden realization.",
      "Encourages responsiveness to external stimuli and shocks.",
      "Symbolizes new energy and awakening through challenges.",
    ],
  },
  {
    number: 52,
    name: "艮",
    pinyin: "Gèn",
    meaning: "Keeping Still (Mountain)",
    interpretations: [
      "Symbolizes stillness and inner reflection.",
      "Encourages meditation and moments of quiet contemplation.",
      "Represents finding stability and peace through stillness.",
    ],
  },
  {
    number: 53,
    name: "渐",
    pinyin: "Jiàn",
    meaning: "Development (Gradual Progress)",
    interpretations: [
      "Represents gradual and steady development.",
      "Encourages patience and steady progress toward objectives.",
      "Symbolizes careful planning and evolving maturity.",
    ],
  },
  {
    number: 54,
    name: "归妹",
    pinyin: "Guī Mèi",
    meaning: "The Marrying Maiden",
    interpretations: [
      "Represents changes in relationships and commitments.",
      "Encourages adaptability to new relational roles.",
      "Symbolizes transitions related to partnerships.",
    ],
  },
  {
    number: 55,
    name: "丰",
    pinyin: "Fēng",
    meaning: "Abundance",
    interpretations: [
      "Symbolizes a time of abundance and productivity.",
      "Encourages enjoying prosperity and fruitful results.",
      "Represents the peak of growth and expansion.",
    ],
  },
  {
    number: 56,
    name: "旅",
    pinyin: "Lǚ",
    meaning: "The Wanderer",
    interpretations: [
      "Represents the journey and exploration of unknowns.",
      "Encourages adaptability and learning from experiences.",
      "Symbolizes wandering, travel, and discovery.",
    ],
  },
  {
    number: 57,
    name: "巽",
    pinyin: "Xùn",
    meaning: "The Gentle (The Penetrating, Wind)",
    interpretations: [
      "Represents subtle influence and gentle penetration.",
      "Encourages clarity through patience and tact.",
      "Symbolizes gradual permeation and adaptability.",
    ],
  },
  {
    number: 58,
    name: "兑",
    pinyin: "Duì",
    meaning: "The Joyous (Lake)",
    interpretations: [
      "Symbolizes joy and open communication.",
      "Encourages sharing happiness and expressing emotions.",
      "Represents a fertile and joyful social environment.",
    ],
  },
  {
    number: 59,
    name: "涣",
    pinyin: "Huàn",
    meaning: "Dispersion (Dissolution)",
    interpretations: [
      "Symbolizes the dispersal of accumulated forces.",
      "Encourages dispersing tension and moving past obstacles.",
      "Represents release and breaking free from constraints.",
    ],
  },
  {
    number: 60,
    name: "节",
    pinyin: "Jié",
    meaning: "Limitation",
    interpretations: [
      "Represents constraint and the importance of limits.",
      "Encourages moderation and appropriate boundaries.",
      "Symbolizes focusing on essentials and disciplined efforts.",
    ],
  },
  {
    number: 61,
    name: "中孚",
    pinyin: "Zhōng Fú",
    meaning: "Inner Truth",
    interpretations: [
      "Symbolizes sincerity and inner truth.",
      "Encourages genuine communication and faithfulness.",
      "Represents the power of truth in persuasion and influence.",
    ],
  },
  {
    number: 62,
    name: "小过",
    pinyin: "Xiǎo Guò",
    meaning: "Preponderance of the Small",
    interpretations: [
      "Represents small excess and careful attention.",
      "Encourages caution in details and small matters.",
      "Symbolizes the importance of finesse and delicacy.",
    ],
  },
  {
    number: 63,
    name: "既济",
    pinyin: "Jì Jì",
    meaning: "After Completion",
    interpretations: [
      "Symbolizes completion and fulfillment.",
      "Encourages careful closure and the implications of finishing.",
      "Represents perfect endings and the transition to new cycles.",
    ],
  },
  {
    number: 64,
    name: "未济",
    pinyin: "Wèi Jì",
    meaning: "Before Completion",
    interpretations: [
      "Symbolizes incomplete efforts and readiness for change.",
      "Encourages preparation before achieving the final goal.",
      "Represents ongoing effort and anticipation of future progress.",
    ],
  },
];
